### PR TITLE
Randomize modparameter

### PR DESCRIPTION
**Pull request by turian**
This allows you to create randomized parameters for the synth. I'd like this for unit-testing numpy vs torch.

Depends upon #33 

What's weird is that the note_on_duration is sometimes disregarded and you get like 16 second samples. Is this because of the one-hit thing @maxsolomonhenry ? That seems like a problem to me. You should be able to hillclimb the synth by setting random params to try to get a similar audio of the same duration :\

### CODE REVIEW

**Comment by maxsolomonhenry** [comment]
As per [this issue](https://github.com/turian/ddsp-drum/issues/27#issue-786093911) we need to reconsider our parameter min-maxs. A 20 second maximum attack will get you into this mess.

**Comment by turian** [comment]
@maxsolomonhenry The issue is orthogonal to the one you're talking about. It's more than if you have a SynthModule (or Drum) and call "randomize_parameters", you don't expect the sound length to change. One you have a synth set up and start flipping around the parameters to find a particular sound, you don't want the sound length to vary.

**Comment by maxsolomonhenry** [comment]
Again we're not hillclimbing note_on_duration. That's a hyperparameter.

If you're randomizing, the audio could have a max time value, based on the Parameter max values.

**Comment by jorshi** [comment]
Randomizing the release time parameter would lead to samples with different lengths, right? Max length of the sample would be note_on_duration + maximum release time. One thing we could do to fix the length of the sound is to introduce another hyperparameter, something like `render_length` -- this could set the length of the output. For example, if the note_on_duration was 1s and that render_length was 2s, then the release time portion would just be cut off at 1s regardless of the actual release time.

**Comment by turian** [comment]
@jorshi yes I like the idea of a render_length hyperparameter.

**Pull request merged**
